# fly.toml file generated for stylelabz-server on 2023-05-01T13:55:36-04:00

app = "stylelabz-server"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "iad"
processes = []

[env]
  PORT = "8080"
  MONGODB_CONNECTION = "mongodb+srv://dzellmer:40EwV0UgYH8DAp2O@cluster0.u1ayvwq.mongodb.net/?retryWrites=true&w=majority"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
