import { Schema } from 'mongoose';
import mongoose from 'mongoose';

// 1. Create an interface representing a document in MongoDB.
interface UserPreferenceInterface {
    userId: Schema.Types.ObjectId,
    //highestClothingScore: string,
    //highestPatternScore: string,
    pastelScore:  string,
    activewearScore: number,
    blazersScore: number,
    coatsScore: number,
    denimScore: number,
    jacketsScore: number,
    jeansScore: number,
    knitwearScore: number,
    pantsScore: number,
    poloShirtsScore: number,
    shirtsScore: number,
    shortsScore: number,
    suitsScore: number,
    tshirtsScore: number,
    otherScore: number,
    solidPatternScore: number,
    floralPatternScore: number,
    spottedPatternScore: number,
    plaidPatternScore: number,
    stripedPatternScore: number,
    graphicsPatternScore: number,
    GrayFamilyColorSchemeScore: number,
    PinkFamilyColorSchemeScore: number,
    BlueFamilyColorSchemeScore: number,
    PurpleFamilyColorSchemeScore: number,
    OrangeFamilyColorSchemeScore: number,
    PastelPaletteScore: number,
    DarkPaletteScore: number,
    BrightPaletteScore: number,
    GoldPaletteScore: number,
    SummerPaletteScore: number,
    TealPaletteScore: number,
    NeutralPaletteScore: number,
}

// 2. Create a Schema corresponding to the document interface.
const UserPreferenceSchema = new Schema<UserPreferenceInterface>({
    userId: { type: Schema.Types.ObjectId, required: true, ref: 'User' },
    //highestClothingScore: String,
    //highestPatternScore: String,
    pastelScore:  String,
    activewearScore: {type:Number, default:0},
    blazersScore: {type:Number, default:0},
    coatsScore: {type:Number, default:0},
    denimScore: {type:Number, default:0},
    jacketsScore: {type:Number, default:0},
    jeansScore: {type:Number, default:0},
    knitwearScore: {type:Number, default:0},
    pantsScore: {type:Number, default:0},
    poloShirtsScore: {type:Number, default:0},
    shirtsScore: {type:Number, default:0},
    shortsScore: {type:Number, default:0},
    suitsScore: {type:Number, default:0},
    tshirtsScore: {type:Number, default:0},
    otherScore: {type:Number, default:0},
    solidPatternScore: {type:Number, default:0},
    floralPatternScore: {type:Number, default:0},
    spottedPatternScore: {type:Number, default:0},
    plaidPatternScore: {type:Number, default:0},
    stripedPatternScore: {type:Number, default:0},
    graphicsPatternScore: {type:Number, default:0},
    GrayFamilyColorSchemeScore: {type:Number, default:0},
    PinkFamilyColorSchemeScore: {type:Number, default:0},
    BlueFamilyColorSchemeScore: {type:Number, default:0},
    OrangeFamilyColorSchemeScore: {type:Number, default:0},
    PastelPaletteScore: {type:Number, default:0},
    DarkPaletteScore: {type:Number, default:0},
    BrightPaletteScore: {type:Number, default:0},
    GoldPaletteScore: {type:Number, default:0},
    SummerPaletteScore: {type:Number, default:0},
    TealPaletteScore: {type:Number, default:0},
    NeutralPaletteScore: {type:Number, default:0},
});

// 3. Create a Model.
export const UserPreferenceModel = mongoose.model('UserPreference', UserPreferenceSchema);
